ARG PYTHON_VERSION
FROM amazonlinux:2

RUN yum -y update && \
    yum -y install gcc libxml2-devel libxslt-devel python${PYTHON_VERSION} python${PYTHON_VERSION}-devel python3-pip zip && \
    alternatives --install /usr/bin/python3 python3 /usr/bin/python${PYTHON_VERSION} 1 && \
    pip3 install --upgrade pip

# Set working directory and copy requirements
WORKDIR /opt/app
COPY requirements.txt .

# Install dependencies
RUN mkdir -p lambda_package && \
    pip3 install -r requirements.txt -t lambda_package/

# Optional: Copy your lambda_function.py into the zip
# COPY lambda_function.py lambda_package/

# Zip everything
RUN cd lambda_package && zip -r ../lambda_package.zip .
